version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  signaling:
    build: ./server
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis

  # Optional: run client in container for dev (you can also run locally)
  client:
    image: node:18
    working_dir: /app/client
    volumes:
      - ./client:/app/client
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    depends_on:
      - signaling
